### ISSUE TITLE
Write guide to help understand logs

### ISSUE THREAD

**Issue by briankelly** [DefinedNet/nebula-docs#10]
stub for `src/data/docs/en/logs.md`

```markdown
---
title: Understanding Nebula Logs
slug: logs
summary: logs
---
#Understanding Nebula Logs
```

**Comment by jasikpark** [comment]
Not sure what we might add here, but documenting *where* logs exist might be helpful, similar to https://docs.defined.net/guides/viewing-dnclient-logs/
