### ISSUE TITLE
Add badges to indicate config values that are reloadable

### ISSUE THREAD

**Issue by IanVS** [DefinedNet/nebula-docs#19]
Changing some values in the config require shutting down and restarting nebula, and some don't.  We should make it clear which can be reloaded (at least in the most recent version of nebula).

**Comment by jasikpark** [comment]
#27 was meant to regard this, but some values are reloadable in different ways and others are reloadable on only some systems, so this was kicked into the future

**Comment by jasikpark** [comment]
Hopefully we can someday remove this ticket by enabling soft-reload for all config items
